source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'GetPods' do
  pod 'Firebase/Core', '0.0.0'

  pod 'Firebase/AdMob', '0.0.0'
  pod 'Firebase/Analytics', '0.0.0'
  pod 'Firebase/Auth', '0.0.0'
  pod 'Firebase/Crashlytics', '0.0.0'
  pod 'Firebase/Database', '0.0.0'
  pod 'Firebase/DynamicLinks', '0.0.0'
  pod 'Firebase/Firestore', '0.0.0'
  pod 'Firebase/Functions', '0.0.0'
  pod 'Firebase/Installations', '0.0.0'
  pod 'FirebaseInstanceID', '0.0.0'
  pod 'Firebase/Messaging', '0.0.0'
  pod 'Firebase/RemoteConfig', '0.0.0'
  pod 'Firebase/Storage', '0.0.0'

end
